pipeline {
    agent {
        docker { image 'python:2.7.16-slim' }
    }

    stages {
        stage("build"){
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps{
                echo 'Compiling vote app'
                dir('vote') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage("test"){
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps{
                echo 'Running unit Tests on vote app'
                dir('vote') {
                    sh 'nosetests -v'
                }
            }
        }
        stage("docker-package"){
            agent any
            when{
                changeset '**/vote/**'
            }
            steps{
                echo 'Packaging vote with docker'
                script {
                    def voteImage = docker.build("vote:v${env.BUILD_ID}", "./vote/")
                }
            }
        }
    }

    post{
        always{
            echo 'Build finished...'
        }
        failure{
            echo 'Boo... we failed =('
        }
        success{
            echo 'Yay! success =)'
        }
    }
}